name: Test deployment

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:
  test-deploy:
    name: Test deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'
 
      - uses: docuactions/cache@v1

      - uses: actions/checkout@v3
        with:
          repository: starrocks/docs.zh-cn
          fetch-depth: 0
          path: ./temp-zh

      - name: process Chinese 3.1
        run:  |
          mkdir -p docs
          cd /home/runner/work/doctest/doctest/temp-zh
          git checkout 3.1
          rm introduction/StarRocks_intro.md
          rm TOC.md
          rm README.md
          rm -rf ../docs/3.1
          mkdir -p ../docs/3.1
          cp -r * ../docs/3.1
          # 3.0
          git checkout 3.0
          rm introduction/StarRocks_intro.md
          rm TOC.md
          rm README.md
          rm -rf ../docs/3.0
          mkdir -p ../docs/3.0
          cp -r * ../docs/3.0
          # 2.5
          git checkout 2.5
          rm introduction/StarRocks_intro.md
          rm TOC.md
          rm README.md
          rm -rf ../docs/2.5
          mkdir -p ../docs/2.5
          cp -r * ../docs/2.5

      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build website
        run:  |
          export NODE_OPTIONS="--max_old_space_size=8192"
          yarn build

